# Pandas Data Input/Output

In this demo I will open a few files saved in my goodle drive.

## Import Pandas

In [ ]:
import pandas as pd

## Read files

- csv-file
- stata-file


After opening the file, check the content with `.head()` method

In [ ]:
df_covid = pd.read_csv("/content/drive/My Drive/data_gv918/data_2020-Oct-14.csv")

In [ ]:
df_covid.head()

  areaType areaName  ... newCasesBySpecimenDate cumCasesBySpecimenDate
0   nation  England  ...                    119                 556528
1   nation  England  ...                   5329                 556409
2   nation  England  ...                   8152                 551080
3   nation  England  ...                   9318                 542928
4   nation  England  ...                  12235                 533610

[5 rows x 6 columns]

In [ ]:
df_bes = pd.read_stata("/content/drive/My Drive/data_gv918/BES2019_W19_v0.5.dta")

In [ ]:
df_bes.head()

      id               starttime  ... p_edlevelUni    p_eurefturnout
0  88493 2019-12-15 18:59:43.774  ...     Postgrad        Yes, voted
1  29164 2019-12-14 00:09:08.573  ...      A-level  No, did not vote
2  68705 2019-12-19 07:16:58.337  ...         GCSE  No, did not vote
3  70863 2019-12-13 16:33:56.153  ...         GCSE        Yes, voted
4  52982 2019-12-18 15:38:39.194  ...         GCSE        Yes, voted

[5 rows x 384 columns]